f_people = ["Gerrard", "Will Smith", "Torres", "Patrick Bateman"]
#message = (f"Hey, {f_people[0].title()} would you like to come to my dinner service")
#print(message)
#message = (f"\nHey, {f_people[1].title()} would you like to come to my dinner service")
#print(message)
#message = (f"\nHey, {f_people[2].title()} would you like to come to my dinner service")
#print(message)
#message = (f"\nHey, {f_people[3].title()} would you like to come to my dinner service")
#print(message)

#print(f"\nSorry to hear you couldn't make it {f_people[1].title()} hopefully you can next time")
#del f_people[1]
#f_people.insert(1, "Jamal")
#message = (f"\nHey, {f_people[1].title()} would you like to come to my dinner service as Will couldnt make it")
#print(message)

#table = "Hey guys i just found a bigger table so we can bring more people"
#print(table)

#f_people.insert(0, "Kara")
#f_people.insert(2, "James")
#f_people.append("Jake")

#message = (f"\nHey, {f_people[0].title()} would you like to come to my dinner service")
#print(message)
#message = (f"\nHey, {f_people[1].title()} would you like to come to my dinner service")
#print(message)
#message = (f"\nHey, {f_people[2].title()} would you like to come to my dinner service")
#print(message)
#message = (f"\nHey, {f_people[3].title()} would you like to come to my dinner service")
#print(message)
#message = (f"\nHey, {f_people[4].title()} would you like to come to my dinner service")
#print(message)
#message = (f"\nHey, {f_people[5].title()} would you like to come to my dinner service")
#print(message)
#message = (f"\nHey, {f_people[6].title()} would you like to come to my dinner service")
#print(message)

#print("Hey sorry guys there was a mixup and we can only bring 2 people to the service now sorry!")
#f_people.remove("Kara")
#f_people.remove("Gerrard")
#f_people.remove("James")
#f_people.remove("Jamal")
#f_people.remove("Torres")
#message = (f"\nHey, {f_people[0].title()} would you like to come to my dinner service sorry about the mix up lol")
#print(message)
#message = (f"\nHey, {f_people[1].title()} would you like to come to my dinner service sorry about the mixup lol")
#print(message)
#del f_people[0]
#del f_people[0]
#print (f_people)

#jobs = ["computer scientist", "gay lord", "ur ma", "penis head"]
#print("Here is the og list")
#print(jobs)

#print("\nHere is the sorted list")
#print(sorted(jobs))

#print("\nHere is the og list again")
#print(jobs)
#jobs.reverse()
#print(jobs)
#jobs_length=len(jobs)
#print("The length of the list jobs is: " + str(jobs_length))

places = ["New York", "Oslo", "Japan", "Sunny Beach", "Thailand"]
print(places)
print("\nReversed List")
print(sorted(places))
print("Original list")
print(places)
print("\nReversed alphabetical list")
print(sorted(places, reverse=True))
print("\nOG list again")
print(places)
print("\nReversed list")
places.reverse()
print(places)
print("\nReversing the list again")
places.reverse()
print(places)
print("\nPutting the list in Alphabetical order with sort() command")
places.sort()
print (places)
print("\nPutting the list in reverse Alphabetical order with sort() command")
places.sort(reverse=True)
print(places)
f_people_length = len(f_people)
print("The length of the f_people list is: " + str (f_people_length))